# Generated by Django 4.2.10 on 2024-02-27 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_price_lesson_price'),
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 19, 23, 43, 335063, tzinfo=datetime.timezone.utc), verbose_name='Последнее посещение'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='learning.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
