# Generated by Django 4.2.10 on 2024-02-27 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_latest_login_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latest_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее посещение'),
        ),
    ]
