# Generated by Django 4.2.10 on 2024-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_latest_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сессия оплаты'),
        ),
    ]
