# Generated by Django 5.0.1 on 2024-02-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
