# Generated by Django 5.0.1 on 2024-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
